name: format

on:
  workflow_dispatch:
  schedule:
    - cron: "0 20 * * *" # UTC+8 04:00

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          show-progress: false

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run format
        run: npm run format

      - name: Commit and push changes
        uses: actions-js/push@master
        with:
          rebase: true
          branch: ${{ github.ref }}
          message: "style: 自动格式化代码

            https://github.com/${{ github.repository
            }}/actions/runs/${{ github.run_id }}

            [skip changelog]"
          github_token: ${{ secrets.GITHUB_TOKEN }}
